### ISSUE TITLE
Windows 运行出错，请教

### ISSUE THREAD

**Issue by Ernest861** [phobal/shadowsocks-free-account#10]
感谢楼主的软件
app.js运行过程中，chromium弹出，只显示了v2ray的账号。然后就弹出错误信息。
win10 64，node v8.10.0,

PS C:\Users\zhdivel> CD .\ShadowSocksSpider\
PS C:\Users\zhdivel\ShadowSocksSpider> node app.js
(node:9452) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\Users\zhdivel\ShadowSocksSpider\node_modules\puppeteer\lib\NavigatorWatcher.js:69:21)
    at <anonymous>
(node:9452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a ca
tch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
 the Node.js process with a non-zero exit code.
(node:9452) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (C:\Users\zhdivel\ShadowSocksSpider\node_modules\puppeteer\lib\Page.js:102:24)
    at Session.Page.client.on.event (C:\Users\zhdivel\ShadowSocksSpider\node_modules\puppeteer\lib\Page.js:97:56)
    at emitOne (events.js:116:13)
    at Session.emit (events.js:211:7)
    at Session._onMessage (C:\Users\zhdivel\ShadowSocksSpider\node_modules\puppeteer\lib\Connection.js:210:12)
    at Connection._onMessage (C:\Users\zhdivel\ShadowSocksSpider\node_modules\puppeteer\lib\Connection.js:105:19)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (C:\Users\zhdivel\ShadowSocksSpider\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\zhdivel\ShadowSocksSpider\node_modules\ws\lib\Receiver.js:389:14)
(node:9452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a ca
tch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by wevsmy** [comment]
me to!

**Comment by wevsmy** [comment]
我使用mac系统试了一下，也是不可以的，只是弹出chromium，具体如下：

wilsondeMac:shadowsocks-free-account-master wilson$ ls
README.md		docs			server
app.js			package-lock.json	src
assets			package.json
wilsondeMac:shadowsocks-free-account-master wilson$ npm i

> puppeteer@0.13.0 install /Users/wilson/Desktop/shadowsocks-free-account-master/node_modules/puppeteer
> node install.js

Downloading Chromium r515411 - 73.2 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/wilson/Desktop/shadowsocks-free-account-master/node_modules/puppeteer/.local-chromium/mac-515411
npm WARN ssspider@0.1.0 No repository field.

added 89 packages in 159.277s
wilsondeMac:shadowsocks-free-account-master wilson$ node app.js 
(node:2154) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/wilson/Desktop/shadowsocks-free-account-master/node_modules/puppeteer/lib/NavigatorWatcher.js:69:21)
    at <anonymous>
(node:2154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by phobal** [comment]
源网站已关闭，所以使用不了了，建议花点小钱买个收费版的吧

**Comment by Ernest861** [comment]
嗯，THX
